.PHONY: clean

openhash:
	@python3 openhash.py

closedhash:
	@python3 closedhash.py

bst:
	@python bst.py

trie:
	@python trie.py

adjmatrix:
	g++ adjmatrix.cpp -o adjmatrix
	./adjmatrix

pot:
	g++ pot.cpp -o pot
	./pot

floyd:
	@python3 floyd.py

dfs:
	@python3 dfs.py

fftdyadic:
	@python3 fftdyadic.py

fftany:
	@python3 fftany.py

clean:
	@\rm -f *.pyc
	@\rm -f pot adjmatrix
