.PHONY: clean

timing:
	@python timing.py

arraylist:
	@python arraylist.py

pointerlist:
	@python pointerlist.py

arraystack:
	@python arraystack.py

pointerstack:
	@python pointerstack.py
	
test:
	@python test.py

clean:
	@\rm -f *.pyc
