.PHONY: clean

openhash:
	@python3 openhash.py

closedhash:
	@python3 closedhash.py

bst:
	@python3 bst.py

trie:
	@python3 trie.py
	
adjmatrix:
	@python3 adjmatrix.py
	
pot:
	@python3 pot.py

floyd:
	@python3 floyd.py

dfs:
	@python3 dfs.py

fftdyadic:
	@python3 fftdyadic.py

fftany:
	@python3 fftany.py

clean:
	@\rm -f *.pyc
